env:
  commonjs: true
  es2020: true
  node: true
  jest/globals: true
extends:
  - airbnb-base
parserOptions:
  ecmaVersion: 11
rules:
  class-methods-use-this: 0
  no-param-reassign: 0
ignorePatterns:
  - node_modules/*
  - jest.config.js
plugins:
  - jest
