name: Java tests

on: [push]

jobs:
  test:

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./java

    steps:
    - uses: actions/checkout@v2
    - name: Clear tool cache
      run: mv "${{ runner.tool_cache }}" "${{ runner.tool_cache }}.old"
    - name: Setup JDK 1.11
      uses: actions/setup-java@v1
      with:
        java-version: 1.11
    - name: Run checks
      run: ./gradlew check