name: NodeJS tests

on: [push]

jobs:
  test:

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./javascript
    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - run: npm test